# The name of your project/route.
# This will be displayed in the header for people who are viewing your route
title: My Project

# The version of your route. There's no particular format here.
# This will be displayed in the metadata in the settings dialog
version: 1.0.0

# This is the route itself. Here it points to the main.yaml file we created earlier
route:
  use: ./main.yaml

# Extra configuration.
# The project must define a map to compile properly.
# For now, we will use the Breath of the Wild celer map maintained by Pistonight
config:
  - use: Pistonight/celer-presets/botw/full.yaml
  - splits:
      - UserDefined
      - Warp
  - plugins:
      - use: variables # required
      - use: link # required
  - tags:
      UserDefined:
        background: orange
        color: black
        split-type: UserDefined
